Github Actions Build Matrix - Parallelization (#39)

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -3,25 +3,26 @@ name: Build and Deploy
 on:
   workflow_dispatch:
   schedule:
-    - cron:  '30 12 * * *' # 6:00 PM IST
+    - cron: "30 11 * * *" # 5:00 PM IST Everyday
 
-concurrency: 
+concurrency:
   group: ${{ github.ref }}
   cancel-in-progress: true
 
 jobs:
-  CheckRecentCommits:
+  check-recent-commits:
+    name: Check Recent Commits
     runs-on: ubuntu-latest
     outputs:
-      hasCommitsInDatabase: ${{ steps.check-new-commits-in-database.outputs.has-new-commits }}
-      hasCommitsInWebserver: ${{ steps.check-new-commits-in-webserver.outputs.has-new-commits }}
+      database_has_changed: ${{ steps.check-new-commits-in-database.outputs.has-new-commits }}
+      webserver_has_changed: ${{ steps.check-new-commits-in-webserver.outputs.has-new-commits }}
     steps:
       - uses: actions/checkout@v2
         with:
           repository: vedupraity/ancientknowledgedatabase
           ref: master
           token: ${{ secrets.PAT_GITHUB_REPO }}
-      
+
       - name: Check commits in ancientknowledgedatabase since 24 hours ago
         id: check-new-commits-in-database
         run: |
@@ -30,13 +31,13 @@ jobs:
           else
             echo "::set-output name=has-new-commits::false"
           fi
-      
+
       - uses: actions/checkout@v2
         with:
           repository: vedupraity/ancientknowledgewebserver
           ref: master
           token: ${{ secrets.PAT_GITHUB_REPO }}
-      
+
       - name: Check commits in ancientknowledgewebserver since 24 hours ago
         id: check-new-commits-in-webserver
         run: |
@@ -46,83 +47,190 @@ jobs:
             echo "::set-output name=has-new-commits::false"
           fi
 
-  Build:
-    needs: CheckRecentCommits
-    if: ${{ needs.CheckRecentCommits.outputs.hasCommitsInDatabase == 'true' || needs.CheckRecentCommits.outputs.hasCommitsInWebserver == 'true' }}
+  fetch-build-urls:
+    name: Fetch Build URLs
+    needs: [check-recent-commits]
+    if: ${{ needs.check-recent-commits.outputs.database_has_changed == 'true' || needs.check-recent-commits.outputs.webserver_has_changed == 'true' }}
     runs-on: ubuntu-latest
+    outputs:
+      build_job_ids: ${{ steps.generate-urls.outputs.build_job_ids }}
     steps:
       - uses: actions/checkout@v2
-        with:
-          repository: vedupraity/ancientknowledgewebserver
-          token: ${{ secrets.PAT_GITHUB_REPO }}
 
       - uses: actions/setup-python@v2
         with:
-          python-version: "3.8"
+          python-version: "3.10.2"
           architecture: "x64"
 
-      - name: 📥 Install
+      - name: Install Requirements
         run: |
-          echo "using: $(python3 --version) and $(pip3 --version)"
           pip3 install -r requirements.txt
 
-      - name: ⚒️ Build
+      - name: Cache Python Environment
+        uses: actions/cache@v2
+        with:
+          path: ${{ env.pythonLocation }}
+          key: python-${{ github.run_number }}
+
+      - name: Generate Freeze Candidate URLs
+        id: generate-urls
         run: |
           source .env.prod
-          python freeze.py
-          echo "finished building all static files"
-          du -h -d 1 build
+          python generate_urls.py
 
-      - name: 💼 Minify
+          echo "::set-output name=build_job_ids::$(cat build_job_ids.json | jq -c)"
+
+      - name: Cache Freeze Candidates
+        uses: actions/cache@v2
+        with:
+          path: |
+            build_job_ids.json
+            urls_per_build_job.json
+          key: freeze-candidates-${{ github.run_number }}
+
+  build-matrix:
+    name: Build Matrix
+    runs-on: ubuntu-latest
+    needs: [fetch-build-urls]
+    strategy:
+      matrix:
+        id: ${{ fromJson(needs.fetch-build-urls.outputs.build_job_ids) }}
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: actions/setup-python@v2
+        with:
+          python-version: "3.10.2"
+          architecture: "x64"
+
+      - name: Cache Python Environment
+        uses: actions/cache@v2
+        with:
+          path: ${{ env.pythonLocation }}
+          key: python-${{ github.run_number }}
+
+      - name: Cache Freeze Candidates
+        uses: actions/cache@v2
+        with:
+          path: |
+            build_job_ids.json
+            urls_per_build_job.json
+          key: freeze-candidates-${{ github.run_number }}
+
+      - name: Freeze URLs
         run: |
-          css-html-js-minify --multiple --overwrite ./build
-          echo "finished optimizing build for production"
-          du -h -d 1 build
+          source .env.prod
 
-      - name: Create Build Cache
+          python freeze_urls.py --build_id=${{ matrix.id }} > >(tee stdout.log) 2> >(tee stderr.log >&2)
+
+          has_error=$(cat stderr.log | grep -i "INTERNAL SERVER ERROR")
+          [[ ! -z $has_error ]] && cat stderr.log && exit 1
+
+          mv build build_${{ matrix.id }}
+
+          du -h -d 1 build_${{ matrix.id }}
+
+      - name: Minify Build
+        run: |
+          css-html-js-minify --multiple --overwrite ./build_${{ matrix.id }}
+
+          du -h -d 1 build_${{ matrix.id }}
+
+      - name: Upload build_${{ matrix.id }} Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: build-artifact-${{ matrix.id }}
+          path: build_${{ matrix.id }}
+
+  consolidate-build:
+    name: Consolidate Build
+    runs-on: ubuntu-latest
+    needs: [build-matrix]
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: actions/setup-python@v2
+        with:
+          python-version: "3.10.2"
+          architecture: "x64"
+
+      - name: Cache Python Environment
+        uses: actions/cache@v2
+        with:
+          path: ${{ env.pythonLocation }}
+          key: python-${{ github.run_number }}
+
+      - name: Cache Freeze Candidates
+        uses: actions/cache@v2
+        with:
+          path: |
+            build_job_ids.json
+            urls_per_build_job.json
+          key: freeze-candidates-${{ github.run_number }}
+
+      - name: Download All Build Artifacts
+        uses: actions/download-artifact@v2
+        with:
+          path: build_artifacts
+
+      - name: Consolidate Builds
+        run: |
+          du -h -d 1 build_artifacts
+
+          mkdir build
+
+          jq -c '.[]' build_job_ids.json | while read id; do
+            rsync -a build_artifacts/build-artifact-${id}/ build/
+          done
+
+      - name: Optimize build for GitHub Pages
+        run: |
+          # move custom 404 page from build/404/index.html to build/404.html
+          mv build/404/index.html build/404.html
+
+          # remove index.html from build/static
+          rm -rf build/static/index.html
+
+          du -h -d 2 build
+
+      - name: Cache Build
         uses: actions/cache@v2
         with:
           path: ./build
-          key: cache-build-dir-${{ github.run_number }}
+          key: build-${{ github.run_number }}
 
-  Deploy:
-    needs: Build
-    if: ${{ needs.CheckRecentCommits.outputs.hasCommitsInDatabase == 'true' || needs.CheckRecentCommits.outputs.hasCommitsInWebserver == 'true' }}
+  deploy:
+    name: Deploy
+    needs: [consolidate-build]
     runs-on: ubuntu-latest
     environment:
       name: production
       url: https://www.ancientknowledge.in
     steps:
-      - name: Check out repo - ancientknowledgewebsite
+      - name: Checkout ancientknowledgewebsite
         uses: actions/checkout@v2
         with:
           repository: vedupraity/ancientknowledgewebsite
           ref: master
           token: ${{ secrets.PAT_GITHUB_REPO }}
 
-      - name: Obtain Build Cache
+      - name: Cache Build
         uses: actions/cache@v2
         with:
           path: ./build
-          key: cache-build-dir-${{ github.run_number }}
+          key: build-${{ github.run_number }}
 
-      - name: 🚀 Deploy
-        env:
-          GITHUB_RUN_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
+      - name: Deploy
         run: |
           cp -rf build/* . && rm -rf build
-          # move custom 404 page from /404/index.html to /404.html
-          mv 404/index.html 404.html
-          # remove index.html from /static
-          rm -rf static/index.html
 
-          date_now_ist="$(TZ=Asia/Kolkata date)"
-          release_name="release-$GITHUB_RUN_NUMBER"
-          echo "$release_name ($date_now_ist)">version.txt
+          release_version="Release-${{ github.run_number }}<br>$(TZ=Asia/Kolkata date)"
+          echo $release_version > version.html
+
+          git status
 
           git config user.email "${{ secrets.GIT_USER_EMAIL }}"
           git config user.name "${{ secrets.GIT_USER_NAME }}"
-          git status
           git add .
-          git commit -m "$release_name ($date_now_ist)"
-          git push origin master
+          git commit -m "$release_version"
+          git push
